sonar.projectKey=city-transition
sonar.projectName=City Transition System
sonar.projectVersion=1.0

sonar.sources=.

# 🔥 VERY IMPORTANT FIX
sonar.exclusions=node_modules/**,coverage/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info