sonar.projectKey=city-transition
sonar.projectName=City Transition System
sonar.projectVersion=1.0

# 🔥 ONLY YOUR CODE
sonar.sources=controllers,routes,models,services

# Safety
sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info