apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aishwaryapj09/city-transition-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://host.docker.internal:27017/city-transition-system"
            - name: JWT_SECRET
              value: "mysecretkey123"

      # 🔥 ADD THIS BLOCK (IMPORTANT FOR FRIEND SYSTEM)
      imagePullSecrets:
        - name: dockerhub-secret
