apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http            # 🔥 ADD THIS (important)
      port: 5000
      targetPort: 5000
      nodePort: 30008
