apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "city-transition-backend"
        metrics_path: /metrics
        static_configs:
          - targets:
              - backend:5000

      - job_name: "prometheus"
        static_configs:
          - targets:
              - localhost:9090

      - job_name: "blackbox-http"
        metrics_path: /probe
        params:
          module:
            - http_2xx
        static_configs:
          - targets:
              - http://backend:5000/api/health
              - http://frontend-service:80
        relabel_configs:
          - source_labels:
              - __address__
            target_label: __param_target
          - source_labels:
              - __param_target
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115

      - job_name: "blackbox-icmp"
        metrics_path: /probe
        params:
          module:
            - icmp
        static_configs:
          - targets:
              - backend
              - frontend-service
        relabel_configs:
          - source_labels:
              - __address__
            target_label: __param_target
          - source_labels:
              - __param_target
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
