sonar.projectKey=city-transition
sonar.projectName=City Transition System
sonar.projectVersion=1.0

# 🔥 ONLY YOUR CODE
sonar.sources=controllers,routes,models,services

# 🔥 STRONG EXCLUSIONS (IMPORTANT)
sonar.exclusions=**/node_modules/**,**/node_modules/.bin/**,**/coverage/**,**/*.exe

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info